DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'RO_USER') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L;', :'RO_USER', :'RO_PASSWORD');
  END IF;
END $$;

\connect :"DB_NAME"

DO $$ DECLARE s text; BEGIN
  FOREACH s IN ARRAY regexp_split_to_array(:'SCHEMAS','\s*,\s*') LOOP
    IF s IS NULL OR length(s)=0 THEN CONTINUE; END IF;
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT SELECT ON TABLES TO %I;', s, :'RO_USER');
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT SELECT ON SEQUENCES TO %I;', s, :'RO_USER');
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT EXECUTE ON FUNCTIONS TO %I;', s, :'RO_USER');

    EXECUTE format('GRANT USAGE ON SCHEMA %I TO %I;', s, :'RO_USER');
    EXECUTE format('GRANT SELECT ON ALL TABLES IN SCHEMA %I TO %I;', s, :'RO_USER');
    EXECUTE format('GRANT SELECT ON ALL SEQUENCES IN SCHEMA %I TO %I;', s, :'RO_USER');
    EXECUTE format('GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA %I TO %I;', s, :'RO_USER');
  END LOOP;
END $$;
