DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'RW_USER') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L;', :'RW_USER', :'RW_PASSWORD');
  END IF;
END $$;

\connect :"DB_NAME"

DO $$ DECLARE s text; BEGIN
  FOREACH s IN ARRAY regexp_split_to_array(:'SCHEMAS','\s*,\s*') LOOP
    IF s IS NULL OR length(s)=0 THEN CONTINUE; END IF;
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO %I;', s, :'RW_USER');
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT USAGE,SELECT ON SEQUENCES TO %I;', s, :'RW_USER');
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT EXECUTE ON FUNCTIONS TO %I;', s, :'RW_USER');

    EXECUTE format('GRANT USAGE ON SCHEMA %I TO %I;', s, :'RW_USER');
    EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA %I TO %I;', s, :'RW_USER');
    EXECUTE format('GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA %I TO %I;', s, :'RW_USER');
    EXECUTE format('GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA %I TO %I;', s, :'RW_USER');
  END LOOP;
END $$;
