services:
  pg:
    working_dir: /
    volumes:
      - "${HOST_SECRETS_DIR:-./.secrets}:${CONTAINER_SECRETS_DIR:-/.secrets}:ro"
    environment:
      TZ: ${TZ:-UTC}
      # *_FILE vars should already be absolute paths INSIDE the container,
      # written by quickpg-build (e.g. /.secrets/pg_superuser.pw)
      POSTGRES_PASSWORD_FILE: ${POSTGRES_SUPERUSER_PASSWORD_FILE}
      DBA_PASSWORD_FILE: ${DBA_PASSWORD_FILE}
      RW_PASSWORD_FILE: ${RW_PASSWORD_FILE}
      RO_PASSWORD_FILE: ${RO_PASSWORD_FILE}

  pgbackups:
    working_dir: /
    volumes:
      - "${HOST_SECRETS_DIR:-./.secrets}:${CONTAINER_SECRETS_DIR:-/.secrets}:ro"
    environment:
      POSTGRES_SUPERUSER_PASSWORD_FILE: ${POSTGRES_SUPERUSER_PASSWORD_FILE}
