version: "3.9"

services:
  pg:
    # No separate profile — this file is only included when file mode is chosen
    environment:
      # switch to *_FILE when this override is active
      POSTGRES_PASSWORD_FILE: ${POSTGRES_SUPERUSER_PASSWORD_FILE}
      POSTGRES_PASSWORD:
      DBA_PASSWORD_FILE: ${DBA_PASSWORD_FILE}
      DBA_PASSWORD:
      RW_PASSWORD_FILE: ${RW_PASSWORD_FILE}
      RW_PASSWORD:
      RO_PASSWORD_FILE: ${RO_PASSWORD_FILE}
      RO_PASSWORD:
    volumes:
      - "${HOST_SECRETS_DIR:-./.secrets}:${CONTAINER_SECRETS_DIR:-/.secrets}:ro"

  pgbackups:
    environment:
      PGPASSWORD_FILE: ${POSTGRES_SUPERUSER_PASSWORD_FILE}
      PGPASSWORD:
    volumes:
      - "${HOST_SECRETS_DIR:-./.secrets}:${CONTAINER_SECRETS_DIR:-/.secrets}:ro"
    command:
      [
        "/bin/sh","-c",
        "chmod +x /usr/local/bin/backup.sh && \
         if [ -n \"$PGPASSWORD_FILE\" ] && [ -r \"$PGPASSWORD_FILE\" ]; then export PGPASSWORD=\"$(cat \"$PGPASSWORD_FILE\")\"; fi && \
         crond -f -l 8"
      ]
