\set ON_ERROR_STOP 1

-- Create application database
CREATE DATABASE IF NOT EXISTS :"APP_DB";

-- Create roles (safe with IF NOT EXISTS in PG 17)
CREATE ROLE IF NOT EXISTS :"DBA_USER"
  LOGIN PASSWORD :'DBA_PASSWORD'
  CREATEDB CREATEROLE;

CREATE ROLE IF NOT EXISTS :"RW_USER"
  LOGIN PASSWORD :'RW_PASSWORD';

CREATE ROLE IF NOT EXISTS :"RO_USER"
  LOGIN PASSWORD :'RO_PASSWORD';

-- Make DBA the owner of the app database
ALTER DATABASE :"APP_DB" OWNER TO :"DBA_USER";

-- Connect to the app DB
\connect :"APP_DB"

-- Schemas
CREATE SCHEMA IF NOT EXISTS partman AUTHORIZATION :"DBA_USER";

-- Public + partman schema usage
GRANT ALL ON SCHEMA public TO :"DBA_USER";
GRANT USAGE ON SCHEMA public TO :"RW_USER", :"RO_USER";
GRANT USAGE ON SCHEMA partman TO :"RW_USER", :"RO_USER";

-- Default privileges
-- Future tables in public, created by DBA_USER
ALTER DEFAULT PRIVILEGES FOR ROLE :"DBA_USER" IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"RW_USER";

ALTER DEFAULT PRIVILEGES FOR ROLE :"DBA_USER" IN SCHEMA public
  GRANT SELECT ON TABLES TO :"RO_USER";

-- Future schemas created by DBA_USER (global, no IN SCHEMA here!)
ALTER DEFAULT PRIVILEGES FOR ROLE :"DBA_USER"
  GRANT USAGE, CREATE ON SCHEMAS TO :"DBA_USER";