-- Create DB
CREATE DATABASE :"APP_DB";

-- Create roles if missing
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'DBA_USER') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L CREATEDB CREATEROLE;', :'DBA_USER', :'DBA_PASSWORD');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'RW_USER') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L;', :'RW_USER', :'RW_PASSWORD');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'RO_USER') THEN
    EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L;', :'RO_USER', :'RO_PASSWORD');
  END IF;
END$$;

ALTER DATABASE :"APP_DB" OWNER TO :"DBA_USER";

\connect :"APP_DB"

CREATE SCHEMA IF NOT EXISTS partman AUTHORIZATION :"DBA_USER";

-- Default privileges
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, CREATE ON SCHEMAS TO :"DBA_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"RW_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO :"RO_USER";

GRANT ALL ON SCHEMA public TO :"DBA_USER";
GRANT USAGE ON SCHEMA public TO :"RW_USER", :"RO_USER";
GRANT USAGE ON SCHEMA partman TO :"RW_USER", :"RO_USER";
