\set ON_ERROR_STOP 1

-- Create database
CREATE DATABASE :"APP_DB";

-- Create roles if not exist
CREATE ROLE :"DBA_USER" LOGIN PASSWORD :'DBA_PASSWORD' CREATEDB CREATEROLE;
CREATE ROLE :"RW_USER"  LOGIN PASSWORD :'RW_PASSWORD';
CREATE ROLE :"RO_USER"  LOGIN PASSWORD :'RO_PASSWORD';

-- Make DBA owner of the database
ALTER DATABASE :"APP_DB" OWNER TO :"DBA_USER";

\connect :"APP_DB"

-- Partman schema
CREATE SCHEMA IF NOT EXISTS partman AUTHORIZATION :"DBA_USER";

-- Default privileges
ALTER DEFAULT PRIVILEGES FOR ROLE :"DBA_USER" IN SCHEMA public
  GRANT USAGE, CREATE ON SCHEMAS TO :"DBA_USER";

ALTER DEFAULT PRIVILEGES FOR ROLE :"DBA_USER" IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"RW_USER";

ALTER DEFAULT PRIVILEGES FOR ROLE :"DBA_USER" IN SCHEMA public
  GRANT SELECT ON TABLES TO :"RO_USER";

-- Schema usage
GRANT ALL ON SCHEMA public TO :"DBA_USER";
GRANT USAGE ON SCHEMA public TO :"RW_USER", :"RO_USER";
GRANT USAGE ON SCHEMA partman TO :"RW_USER", :"RO_USER";
